CREATE TABLE `a_user` (
  `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) COLLATE utf8_bin NOT NULL,
  `name` VARCHAR(64) COLLATE utf8_bin NOT NULL,
  `surname` VARCHAR(64) COLLATE utf8_bin NOT NULL,
  `password` VARCHAR(256) COLLATE utf8_bin NOT NULL,
  `email` VARCHAR(64) COLLATE utf8_bin NOT NULL,
  `phone_code` VARCHAR(3) COLLATE utf8_bin NOT NULL,
  `phone` VARCHAR(64) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin